export const appEnvs = {
  REACT_APP_GITHUB_USERNAME: process.env.REACT_APP_GITHUB_USERNAME,
  REACT_APP_GITHUB_API_KEY: process.env.REACT_APP_GITHUB_API_KEY,
  REACT_APP_CONTACT_US_RECEIVER_EMAIL: process.env.REACT_APP_CONTACT_US_RECEIVER_EMAIL,
};
